---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
  labels:
    app: books
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: books
  replicas: 1
  template:
    metadata:
      labels:
        app: books
    spec:
      securityContext:
        runAsUser: 1000
      restartPolicy: Always
      containers:
      - name: books
        image: andreajuanmaurjc/cd-practica-1:1.0.0
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/test
        ports:
        - containerPort: 8881
---
apiVersion: v1
kind: Service
metadata:
  name: books
  labels:
    app: books
spec:
  ports:
  - port: 8881
    targetPort: 8881
    nodePort: 30000
    protocol: TCP
    name: books-port
  selector:
    app: books
  type: NodePort